@extends('layouts.app',['title'=>'Visão geral — Sinala'])
@section('content')
<div class="mx-auto max-w-[1500px]">
  <div class="flex flex-wrap items-end justify-between gap-4">
    <div><p class="text-sm text-stone-400">Bom dia, {{ explode(' ',auth()->user()->name)[0] }}</p><h1 class="mt-1 text-3xl font-bold tracking-tight">Visão geral</h1></div>
    <div class="flex gap-2"><a href="{{ route('events.index') }}" class="btn-secondary">Ver eventos</a><a href="{{ route('events.create') }}" class="btn-primary">+ Novo evento</a></div>
  </div>

  <section aria-label="Indicadores principais" class="mt-7 grid overflow-hidden rounded-2xl border border-stone-200 bg-white sm:grid-cols-2 xl:grid-cols-4">
    @foreach([
      ['Eventos',$stats['events'],'+'.$stats['upcoming'].' próximos','M4 16l4-5 4 3 6-8'],
      ['Participantes',$stats['participants'],$stats['present'].' presentes','M4 18c0-3 3-5 6-5s6 2 6 5M10 10a3 3 0 100-6 3 3 0 000 6z'],
      ['Taxa de presença',$stats['attendance_rate'].'%',$stats['signatures'].' assinaturas','M4 12l5 5L20 6'],
      ['Valor distribuído',number_format($stats['distributed'],0,',','.').' MT',$stats['completed'].' eventos concluídos','M4 7h16M6 11h3m-3 4h5m5-4h2']
    ] as [$label,$value,$note,$path])
    <article class="group relative min-h-36 border-stone-200 p-5 sm:[&:not(:nth-child(2n))]:border-r xl:[&:not(:last-child)]:border-r">
      <div class="flex items-start justify-between"><small class="font-medium text-stone-500">{{ $label }}</small><span class="grid size-8 place-items-center rounded-lg bg-orange-50 text-orange-600"><svg class="size-4" fill="none" stroke="currentColor" stroke-width="1.8" viewBox="0 0 24 24"><path d="{{ $path }}"/></svg></span></div>
      <strong class="mt-3 block text-3xl font-semibold tracking-tight">{{ $value }}</strong><span class="mt-2 block text-xs text-emerald-600">↗ {{ $note }}</span>
      <svg class="absolute bottom-3 right-4 h-7 w-20 text-orange-400 opacity-70" viewBox="0 0 80 28" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M1 22L10 18l8 3 9-12 9 8 8-5 9 7 10-13 8 7 8-5"/></svg>
    </article>@endforeach
  </section>

  <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
    <section class="overflow-hidden rounded-2xl border border-stone-200 bg-white">
      <div class="flex flex-wrap items-center justify-between gap-3 border-b border-stone-200 p-5"><div><h2 class="text-lg font-bold">Eventos recentes</h2><p class="mt-1 text-sm text-stone-400">Actividades da organização e progresso de presenças</p></div><div class="flex gap-2"><label class="relative"><span class="sr-only">Pesquisar eventos</span><input id="event-search" class="h-10 w-44 rounded-xl border border-stone-200 pl-9 pr-3 text-sm" placeholder="Pesquisar"><span class="absolute left-3 top-2 text-stone-400">⌕</span></label><a href="{{ route('events.index') }}" class="grid size-10 place-items-center rounded-xl border border-stone-200" title="Todos os eventos">→</a></div></div>
      <div class="flex gap-5 overflow-x-auto border-b border-stone-100 px-5 text-sm"><button class="event-filter active py-4" data-status="all">Todos</button><button class="event-filter py-4" data-status="ongoing">Em curso</button><button class="event-filter py-4" data-status="scheduled">Agendados</button><button class="event-filter py-4" data-status="completed">Concluídos</button></div>
      <div class="overflow-x-auto"><table class="min-w-[760px] w-full text-left text-sm"><thead><tr><th>Evento</th><th>Data</th><th>Estado</th><th>Participantes</th><th>Progresso</th><th></th></tr></thead><tbody id="event-rows">@forelse($recentEvents as $event)@php($progress=$event->participants_count ? min(100,round($event->attendance_records_count/$event->participants_count*100)) : 0)<tr data-event-row data-status="{{ $event->status }}" data-name="{{ mb_strtolower($event->name) }}"><td><a class="font-semibold hover:text-orange-600" href="{{ route('events.show',$event) }}">{{ $event->name }}</a><small class="mt-1 block text-stone-400">{{ $event->location }}</small></td><td class="whitespace-nowrap">{{ $event->starts_on->format('d/m/Y') }}</td><td><span class="status-pill status-{{ $event->status }}">{{ ['draft'=>'Rascunho','scheduled'=>'Agendado','ongoing'=>'Em curso','completed'=>'Concluído','cancelled'=>'Cancelado'][$event->status]??$event->status }}</span></td><td>{{ $event->participants_count }}</td><td><div class="flex items-center gap-3"><div class="h-1.5 w-20 overflow-hidden rounded-full bg-stone-100"><i class="block h-full rounded-full bg-orange-500" style="width:{{ $progress }}%"></i></div><small>{{ $progress }}%</small></div></td><td><a aria-label="Abrir {{ $event->name }}" href="{{ route('events.show',$event) }}">•••</a></td></tr>@empty<tr><td colspan="6" class="py-12 text-center text-stone-400">Ainda não existem eventos. <a class="text-orange-600" href="{{ route('events.create') }}">Criar primeiro evento</a></td></tr>@endforelse</tbody></table></div>
    </section>

    <aside class="space-y-6">
      <section class="rounded-2xl border border-stone-200 bg-white p-5"><div class="flex items-start justify-between"><div><small class="text-stone-400">Plano actual</small><h2 class="mt-1 text-xl font-bold">{{ $usage['plan']?->name ?? 'Sem plano' }}</h2></div><span class="rounded-full bg-orange-50 px-3 py-1 text-xs font-bold text-orange-600">{{ $usage['percentage'] }}%</span></div><div class="mt-6"><div><strong class="text-3xl">{{ $usage['used'] }}</strong><span class="text-stone-400"> / {{ $usage['limit'] }}</span></div><small class="mt-1 block text-stone-400">eventos utilizados {{ $usage['period'] }}, até ao limite do plano</small></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-stone-100"><div class="h-full rounded-full {{ $usage['percentage']>=90?'bg-red-500':'bg-orange-500' }}" style="width:{{ $usage['percentage'] }}%"></div></div><p class="mt-3 text-sm text-stone-500">Pode criar mais <strong class="text-stone-800">{{ $usage['remaining'] }}</strong> {{ Str::plural('evento',$usage['remaining']) }}.</p>@if($usage['percentage']>=70)<p class="mt-4 text-sm text-amber-700">{{ $usage['percentage']>=100?'Atingiu o limite de eventos.':'Está próximo do limite do seu pacote.' }}</p>@endif<button class="btn-secondary mt-5 w-full">Fazer upgrade</button></section>
      <section class="rounded-2xl bg-stone-950 p-5 text-white"><small class="text-stone-400">Acção rápida</small><h2 class="mt-2 text-xl font-bold">Recolher assinaturas</h2><p class="mt-2 text-sm leading-6 text-stone-400">Abra um evento no modo tablet e registe presenças em poucos toques.</p>@if($recentEvents->first())<a class="mt-5 inline-flex items-center gap-2 font-bold text-orange-400" href="{{ route('attendance.kiosk',$recentEvents->first()) }}">Abrir modo assinatura →</a>@else<a class="mt-5 inline-flex items-center gap-2 font-bold text-orange-400" href="{{ route('events.create') }}">Criar evento →</a>@endif</section>
    </aside>
  </div>
</div>
@push('scripts')<script>const search=document.querySelector('#event-search'),filters=document.querySelectorAll('.event-filter'),rows=document.querySelectorAll('[data-event-row]');let status='all';function filterRows(){const q=(search?.value||'').toLowerCase();rows.forEach(row=>row.hidden=!((status==='all'||row.dataset.status===status)&&row.dataset.name.includes(q)))}search?.addEventListener('input',filterRows);filters.forEach(button=>button.addEventListener('click',()=>{filters.forEach(b=>b.classList.remove('active'));button.classList.add('active');status=button.dataset.status;filterRows()}));</script>@endpush
@endsection
