@extends('layouts.app',['title'=>$event->name.' — Sinala'])
@section('content')
<div class="flex flex-wrap items-start justify-between gap-5">
  <div><span class="badge-success">{{ ['draft'=>'Rascunho','scheduled'=>'Agendado','ongoing'=>'Em curso','completed'=>'Concluído','cancelled'=>'Cancelado'][$event->status] ?? $event->status }}</span><h1 class="mt-3 text-4xl font-bold">{{ $event->name }}</h1><p class="mt-2 text-stone-500">{{ $event->location }} · {{ $event->starts_on->format('d/m/Y') }} — {{ $event->ends_on->format('d/m/Y') }}</p></div>
  <div class="flex flex-wrap gap-3"><a class="btn-secondary" href="{{ route('exports.attendance',$event) }}">↓ Exportar presença PDF</a><a class="btn-primary" href="{{ route('attendance.kiosk',$event) }}">Modo de assinatura</a></div>
</div>

<div class="mt-8 grid gap-6 xl:grid-cols-[1fr_360px]">
  <div class="space-y-6">
    <section class="rounded-3xl bg-white p-6"><div class="flex justify-between"><h2 class="text-2xl font-bold">Participantes</h2><strong>{{ $event->participants->count() }}</strong></div><div class="mt-5 overflow-auto"><table class="w-full text-left"><thead><tr><th>Nome</th><th>Organização</th><th>Telefone</th><th>Estado</th></tr></thead><tbody>@foreach($event->participants as $p)<tr><td>{{ $p->full_name }}</td><td>{{ $p->company ?: '—' }}</td><td>{{ $p->phone ?: '—' }}</td><td><span class="badge-success">{{ $p->pivot->status }}</span></td></tr>@endforeach</tbody></table></div></section>

    <section class="rounded-3xl bg-white p-6"><div class="flex items-center justify-between"><div><h2 class="text-2xl font-bold">Listas de pagamento</h2><p class="mt-1 text-sm text-stone-500">Somente participantes desta lista de presença são incluídos. O recebimento exige assinatura.</p></div><strong>{{ $event->paymentLists->count() }}</strong></div><div class="mt-5 space-y-3">@forelse($event->paymentLists as $list)<div class="flex flex-wrap items-center justify-between gap-3 rounded-2xl border p-4"><div><strong>{{ $list->name }}</strong><p class="mt-1 text-sm text-stone-500">{{ $list->type }} · {{ number_format($list->default_amount,2,',','.') }} {{ $list->currency }}</p></div><div class="flex flex-wrap gap-2"><a class="btn-primary" href="{{ route('payments.lists.show',$list) }}">Abrir e recolher assinaturas</a><a class="btn-secondary" href="{{ route('exports.payment',$list) }}">↓ PDF</a></div></div>@empty<p class="rounded-2xl bg-stone-50 p-5 text-sm text-stone-500">Ainda não existem listas de pagamento neste evento.</p>@endforelse</div></section>
  </div>

  <aside class="space-y-6">
    <form method="post" action="{{ route('participants.store',$event) }}" class="rounded-3xl bg-white p-6">@csrf<h2 class="text-xl font-bold">Adicionar participante</h2><div class="mt-5 space-y-4"><label class="field">Nome completo<input name="full_name" required></label><label class="field">Telefone<input name="phone"></label><label class="field">E-mail<input name="email" type="email"></label><label class="field">Organização<input name="company"></label><label class="field">Sexo<select name="sex"><option value="">Seleccionar</option><option value="female">Feminino</option><option value="male">Masculino</option><option value="other">Outro</option></select></label><button class="btn-primary w-full">Adicionar</button></div></form>
    <form method="post" action="{{ route('payments.lists.store',$event) }}" class="rounded-3xl bg-stone-950 p-6 text-white">@csrf<h2 class="text-xl font-bold">Nova lista de pagamento</h2><p class="mt-2 text-sm leading-6 text-stone-400">Apenas as pessoas da lista de presença serão adicionadas. Todas começam como pendentes.</p><div class="mt-5 space-y-4"><label class="field dark">Nome<input name="name" required></label><label class="field dark">Tipo<input name="type" value="Subsídio de transporte" required></label><label class="field dark">Valor padrão<input name="default_amount" type="number" step="0.01" required></label><label class="field dark">Moeda<select name="currency"><option>MZN</option><option>USD</option><option>EUR</option><option>ZAR</option></select></label><label class="field dark">Data<input name="payment_date" type="date" required value="{{ today()->format('Y-m-d') }}"></label><button class="btn-primary w-full">Criar lista</button></div></form>
  </aside>
</div>
@endsection
