@extends('layouts.app',['title'=>$event->name.' — Sinala'])
@section('content')
<div class="flex flex-wrap items-start justify-between gap-5">
  <div><span class="badge-success">{{ ['draft'=>'Rascunho','scheduled'=>'Agendado','ongoing'=>'Em curso','completed'=>'Concluído','cancelled'=>'Cancelado'][$event->status] ?? $event->status }}</span>@if($event->isClosed())<span class="status-pill status-closed ml-2">Fechado</span>@endif<h1 class="mt-3 text-4xl font-bold">{{ $event->name }}</h1><p class="mt-2 text-stone-500">{{ $event->location }} · {{ $event->starts_on->format('d/m/Y') }} — {{ $event->ends_on->format('d/m/Y') }}</p></div>
  <div class="flex flex-wrap gap-3">@can('editEventDetails',$event)<a class="btn-secondary" href="{{ route('events.edit',$event) }}">Editar evento</a>@endcan<a class="btn-secondary" href="{{ route('exports.attendance',$event) }}">↓ Exportar presença PDF</a>@if($event->paymentLists->count())<a class="btn-secondary" href="{{ route('exports.payments',$event) }}">↓ Baixar todas as listas (PDF)</a>@endif @can('managePayments',$event)<a class="btn-primary" href="{{ route('attendance.kiosk',$event) }}">Modo de assinatura</a>@endcan
@can('close',$event)<form method="post" action="{{ route('events.close',$event) }}" onsubmit="return confirm('Fechar este evento? Deixará de ser possível editar dados, presenças, pagamentos ou participantes.')">@csrf<button class="btn-primary bg-stone-900">Fechar evento</button></form>@endcan</div>
</div>
@if($event->isClosed())<div class="mt-5 rounded-2xl bg-stone-900 p-5 text-white">Evento fechado em {{ $event->closed_at->format('d/m/Y H:i') }}{{ $event->closedBy ? ' por '.$event->closedBy->name : '' }}. Os dados continuam disponíveis apenas para consulta, relatórios e exportação.</div>@endif

<div class="mt-8 grid gap-6 xl:grid-cols-[1fr_360px]">
  <div class="space-y-6">
    <section class="rounded-3xl bg-white p-6"><div class="flex justify-between"><h2 class="text-2xl font-bold">Participantes</h2><strong>{{ $event->participants_count }}</strong></div><div class="mt-5 overflow-auto"><table class="w-full text-left"><caption class="sr-only">Participantes do evento</caption><thead><tr><th>Nome</th><th>Organização</th><th>Telefone</th><th>Estado</th></tr></thead><tbody>@foreach($participants as $p)<tr><td>{{ $p->full_name }}</td><td>{{ $p->company ?: '—' }}</td><td>{{ $p->phone ?: '—' }}</td><td><span class="badge-success">{{ $p->pivot->status }}</span></td></tr>@endforeach</tbody></table></div><div class="mt-5">{{ $participants->links() }}</div></section>

    <section class="rounded-3xl bg-white p-6"><div class="flex items-center justify-between"><h2 class="text-2xl font-bold">Listas de pagamento</h2><strong>{{ $event->paymentLists->count() }}</strong></div><p class="mt-1 text-sm text-stone-500">Geradas a partir dos participantes marcados como presentes. O recebimento exige assinatura.</p><div class="mt-5 space-y-3">@forelse($event->paymentLists as $list)<div class="flex flex-wrap items-center justify-between gap-3 rounded-2xl border p-4"><div><strong>{{ $list->name }}</strong><p class="mt-1 text-sm text-stone-500">{{ $list->type }} · {{ number_format($list->default_amount,2,',','.') }} {{ $list->currency }}</p></div><div class="flex flex-wrap gap-2"><a class="btn-primary" href="{{ route('payments.lists.show',$list) }}">Abrir e recolher assinaturas</a><a class="btn-secondary" href="{{ route('exports.payment',$list) }}">↓ PDF</a></div></div>@empty<p class="rounded-2xl bg-stone-50 p-5 text-sm text-stone-500">Ainda não existem listas de pagamento neste evento.</p>@endforelse</div></section>
  </div>

  <aside class="space-y-6">
    @can('manageParticipants',$event)<form method="post" action="{{ route('participants.store',$event) }}" class="rounded-3xl bg-white p-6">@csrf<h2 class="text-xl font-bold">Adicionar participante</h2><div class="mt-5 space-y-4"><label class="field">Nome completo<input name="full_name" required></label><label class="field">Telefone<input name="phone"></label><label class="field">E-mail<input name="email" type="email"></label><label class="field">Organização<input name="company"></label><label class="field">Sexo<select name="sex"><option value="">Seleccionar</option><option value="female">Feminino</option><option value="male">Masculino</option><option value="other">Outro</option></select></label><button class="btn-primary w-full">Adicionar</button></div></form>@endcan
    @can('managePayments',$event)<div class="rounded-3xl bg-stone-950 p-6 text-white"><h2 class="text-xl font-bold">Nova lista de pagamento</h2><p class="mt-2 text-sm leading-6 text-stone-400">Escolha quem esteve presente antes de gerar a lista. Todas começam como pendentes.</p><a class="btn-primary mt-5 block w-full text-center" href="{{ route('payments.lists.create',$event) }}">Marcar presenças e criar lista</a></div>@endcan
  </aside>
</div>
@endsection
