<!doctype html><html lang="pt"><head><meta charset="utf-8"><style>
@page{margin:24px}body{font-family:DejaVu Sans,sans-serif;font-size:9px;color:#111}.header{width:100%;margin-bottom:16px}.header td{vertical-align:top}.header-banner{display:block;width:100%;max-height:72px;object-fit:contain}.logo{max-width:125px;max-height:55px}.org{text-align:right;font-size:10px;font-weight:bold}.title{text-align:center;font-size:15px;margin:10px 0 14px;text-transform:uppercase}.meta{line-height:1.7;margin-bottom:10px}.consent{font-weight:bold;margin:10px 0}table.list{width:100%;border-collapse:collapse}.list th,.list td{border:1px solid #777;padding:5px}.list th{background:#f0f0ed;text-align:left;font-size:8px}.center{text-align:center}.signature{max-width:90px;max-height:28px}.signers{width:100%;margin-top:34px;page-break-inside:avoid}.signers td{width:50%;padding:0 35px;text-align:center}.line{border-top:1px solid #111;padding-top:5px;margin-top:28px}.muted{color:#555;font-size:8px}.platform-footer{margin-top:24px;text-align:center;border-top:1px solid #ddd;padding-top:8px}.platform-footer img{height:18px;vertical-align:middle;margin-left:5px}
</style></head><body>
@if($headerBannerData)<img class="header-banner" src="{{ $headerBannerData }}">@else<table class="header"><tr><td><img class="logo" src="{{ $logoData ?: public_path('brand/sinala-logo-transparent.png') }}"></td><td class="org">{{ $settings['header_title'] ?? $event->organization->name }}<br><span class="muted">{{ $settings['header_subtitle'] ?? 'Documento oficial' }}</span></td></tr></table>@endif
<h1 class="title">Lista de Presença</h1>
<div class="meta">@if(!empty($settings['project_name']))<strong>Projecto:</strong> {{ $settings['project_name'] }}<br>@endif @if(!empty($settings['funding_reference']))<strong>Referência:</strong> {{ $settings['funding_reference'] }}<br>@endif<strong>Actividade:</strong> {{ $event->name }}<br><strong>Local:</strong> {{ $event->location }} &nbsp;&nbsp; <strong>Período:</strong> {{ $event->starts_on->format('d/m/Y') }} a {{ $event->ends_on->format('d/m/Y') }} @if($event->starts_at) &nbsp;&nbsp; <strong>Horário:</strong> {{ substr($event->starts_at,0,5) }}–{{ substr($event->ends_at,0,5) }} @endif</div>
<p class="consent">Ao assinar esta lista de presença, confirmo a minha participação na actividade indicada.</p>
<table class="list"><thead><tr><th>N.º</th><th>Nome</th><th>Género</th><th>Instituição</th><th>Contacto</th>@foreach($event->days as $day)<th>{{ $day->date->format('d/m') }}<br>Entrada / assinatura</th>@if($event->requires_check_out)<th>{{ $day->date->format('d/m') }}<br>Saída / assinatura</th>@endif @endforeach</tr></thead><tbody>
@foreach($event->participants as $participant)<tr><td class="center">{{ $loop->iteration }}</td><td><strong>{{ $participant->full_name }}</strong></td><td>{{ ['female'=>'Feminino','male'=>'Masculino','other'=>'Outro'][$participant->sex] ?? '—' }}</td><td>{{ $participant->company ?: '—' }}</td><td>{{ $participant->phone ?: '—' }}</td>@foreach($event->days as $day)@php($entry=$records->get($day->id.'-'.$participant->id.'-check_in'))<td class="center">@if($entry)<span class="muted">{{ $entry->recorded_at->format('H:i') }}</span><br>@if($src=\App\Http\Controllers\ExportController::signatureData($entry->signature?->path))<img class="signature" src="{{ $src }}">@endif @else — @endif</td>@if($event->requires_check_out)@php($exit=$records->get($day->id.'-'.$participant->id.'-check_out'))<td class="center">@if($exit)<span class="muted">{{ $exit->recorded_at->format('H:i') }}</span><br>@if($src=\App\Http\Controllers\ExportController::signatureData($exit->signature?->path))<img class="signature" src="{{ $src }}">@endif @else — @endif</td>@endif @endforeach</tr>@endforeach
</tbody></table>
<table class="signers"><tr>@forelse($managers as $manager)<td><div class="line"><strong>{{ $manager->name }}</strong><br>{{ $manager->roles->pluck('name')->first() }}<br><span class="muted">Assinatura do responsável da organização</span></div></td>@empty<td><div class="line">Responsável da organização</div></td>@endforelse</tr></table>
@if(!empty($settings['footer_note']))<p class="muted" style="margin-top:24px;text-align:center">{{ $settings['footer_note'] }}</p>@endif
<div class="platform-footer muted">Documento gerado pela plataforma <a href="https://sinala.mazedeve.com">Sinala</a> (https://sinala.mazedeve.com)</div>
</body></html>
