<!doctype html><html lang="pt"><head><meta charset="utf-8"><style>
@page{margin:24px}body{font-family:DejaVu Sans,sans-serif;font-size:9px;color:#111}.header{width:100%;margin-bottom:16px}.header td{vertical-align:top}.header-banner{display:block;width:100%;max-height:72px;object-fit:contain}.logo{max-width:125px;max-height:55px}.org{text-align:right;font-size:10px;font-weight:bold}.title{text-align:center;font-size:15px;margin:10px 0 14px;text-transform:uppercase}.meta{line-height:1.7;margin-bottom:14px}table.list{width:100%;border-collapse:collapse}.list th,.list td{border:1px solid #777;padding:6px}.list th{background:#f0f0ed;text-align:left;font-size:8px}.center{text-align:center}.money{text-align:right;white-space:nowrap}.signature{max-width:90px;max-height:28px}.total{font-weight:bold;background:#f0f0ed}.signers{width:100%;margin-top:34px;page-break-inside:avoid}.signers td{width:50%;padding:0 35px;text-align:center}.line{border-top:1px solid #111;padding-top:5px;margin-top:28px}.muted{color:#555;font-size:8px}.platform-footer{margin-top:24px;text-align:center;border-top:1px solid #ddd;padding-top:8px}.platform-footer img{height:18px;vertical-align:middle;margin-left:5px}
</style></head><body>
@if($headerBannerData)<img class="header-banner" src="{{ $headerBannerData }}">@else<table class="header"><tr><td><img class="logo" src="{{ $logoData ?: public_path('brand/sinala-logo-transparent.png') }}"></td><td class="org">{{ $settings['header_title'] ?? $event->organization->name }}<br><span class="muted">{{ $settings['header_subtitle'] ?? 'Documento oficial' }}</span></td></tr></table>@endif
<h1 class="title">Lista de Pagamento de Subsídios</h1>
<div class="meta">@if(!empty($settings['project_name']))<strong>Projecto:</strong> {{ $settings['project_name'] }}<br>@endif @if(!empty($settings['funding_reference']))<strong>Referência:</strong> {{ $settings['funding_reference'] }}<br>@endif<strong>Actividade:</strong> {{ $event->name }}<br><strong>Lista:</strong> {{ $paymentList->name }} &nbsp;&nbsp; <strong>Tipo:</strong> {{ $paymentList->type }}<br><strong>Local:</strong> {{ $event->location }} &nbsp;&nbsp; <strong>Data:</strong> {{ $paymentList->payment_date->format('d/m/Y') }}</div>
<table class="list"><thead><tr><th>N.º</th><th>Nome completo</th><th>Instituição</th><th>Contacto</th><th>Valor ({{ $paymentList->currency }})</th><th>Estado</th><th>Data/hora</th><th>Assinatura</th></tr></thead><tbody>
@foreach($paymentList->payments as $payment)<tr><td class="center">{{ $loop->iteration }}</td><td><strong>{{ $payment->participant->full_name }}</strong></td><td>{{ $payment->participant->company ?: '—' }}</td><td>{{ $payment->participant->phone ?: '—' }}</td><td class="money">{{ number_format($payment->amount,2,',','.') }}</td><td>{{ $payment->status === 'paid' ? 'Pago' : 'Pendente' }}</td><td>{{ $payment->paid_at?->format('d/m/Y H:i') ?: '—' }}</td><td class="center">@if($src=\App\Http\Controllers\ExportController::signatureData(($attendanceSignatures->get($payment->participant_id)?->path) ?: $payment->signature?->path))<img class="signature" src="{{ $src }}">@else — @endif</td></tr>@endforeach
<tr class="total"><td colspan="4" class="money">TOTAL PAGO</td><td class="money">{{ number_format($paymentList->payments->where('status','paid')->sum('amount'),2,',','.') }} {{ $paymentList->currency }}</td><td colspan="3"></td></tr></tbody></table>
<table class="signers"><tr>@forelse($managers as $manager)<td><div class="line"><strong>{{ $manager->name }}</strong><br>{{ $manager->roles->pluck('name')->first() }}<br><span class="muted"></span></div></td>@empty<td><div class="line">Responsável da organização</div></td>@endforelse</tr></table>
@if(!empty($settings['footer_note']))<p class="muted" style="margin-top:24px;text-align:center">{{ $settings['footer_note'] }}</p>@endif
<div class="platform-footer muted">Documento gerado pela plataforma <a href="https://sinala.mazedeve.com">Sinala</a> (https://sinala.mazedeve.com)</div>
</body></html>
