@extends('layouts.app',['title'=>$paymentList->name.' — Pagamentos'])
@section('content')
<div class="mx-auto max-w-[1500px]">
  <div class="flex flex-wrap items-start justify-between gap-5"><div><a class="text-sm font-semibold text-orange-600" href="{{ route('events.show',$paymentList->event) }}">← {{ $paymentList->event->name }}</a><p class="eyebrow mt-5">PAGAMENTOS / SUBSÍDIOS</p><h1 class="mt-2 text-4xl font-bold">{{ $paymentList->name }}</h1><p class="mt-2 text-stone-500">{{ $paymentList->type }} · {{ $paymentList->payment_date->format('d/m/Y') }}</p></div><a class="btn-secondary" href="{{ route('exports.payment',$paymentList) }}">↓ Exportar PDF</a></div>
  <div class="mt-7 grid gap-4 sm:grid-cols-3"><article class="metric"><small>Total previsto</small><strong>{{ number_format($stats['expected'],2,',','.') }} {{ $paymentList->currency }}</strong></article><article class="metric"><small>Total pago</small><strong>{{ number_format($stats['paid'],2,',','.') }} {{ $paymentList->currency }}</strong></article><article class="metric"><small>Confirmações</small><strong>{{ $stats['confirmed'] }} / {{ $stats['count'] }}</strong></article></div>
  <section class="mt-6 overflow-hidden rounded-3xl border border-stone-200 bg-white"><div class="border-b p-5"><h2 class="text-xl font-bold">Participantes da lista de presença</h2><p class="mt-1 text-sm text-stone-500">A pessoa só passa para “Pago” depois de confirmar o valor e assinar.</p><form method="get" class="mt-4 grid max-w-3xl gap-3 sm:grid-cols-[1fr_150px_110px_auto]"><label class="field">Pesquisar<input name="search" value="{{ request('search') }}" placeholder="Nome do participante"></label><label class="field">Estado<select name="status"><option value="">Todos</option><option value="pending" @selected(request('status')==='pending')>Pendente</option><option value="paid" @selected(request('status')==='paid')>Pago</option></select></label><label class="field">Por página<select name="per_page">@foreach([10,20,50,100] as $size)<option @selected((int)request('per_page',20)===$size)>{{ $size }}</option>@endforeach</select></label><div class="flex items-end"><button class="btn-primary">Filtrar</button></div></form></div>
    <div class="overflow-x-auto"><table class="w-full min-w-[820px] text-left"><caption class="sr-only">Pagamentos dos participantes</caption><thead><tr><th>N.º</th><th>Participante</th><th>Valor</th><th>Estado</th><th>Confirmação</th><th></th></tr></thead><tbody>@foreach($payments as $payment)<tr><td>{{ $payments->firstItem()+$loop->index }}</td><td><strong>{{ $payment->participant->full_name }}</strong><small class="mt-1 block text-stone-400">{{ $payment->participant->company ?: 'Lista de presença do evento' }}</small></td><td class="font-bold">@if($payment->status==='paid'){{ number_format($payment->amount,2,',','.') }} {{ $paymentList->currency }}@else<form method="post" action="{{ route('payments.amount.update',$payment) }}" class="flex items-center gap-2"><label class="sr-only" for="amount-{{ $payment->id }}">Valor de {{ $payment->participant->full_name }}</label>@csrf @method('put')<input id="amount-{{ $payment->id }}" name="amount" type="number" step="0.01" min="0" value="{{ $payment->amount }}" class="w-28 rounded-lg border border-stone-300 px-2 py-1 text-right"><span class="text-stone-400">{{ $paymentList->currency }}</span><button class="btn-secondary min-h-9 px-3 text-sm">Guardar</button></form>@endif</td><td><span class="{{ $payment->status==='paid'?'badge-success':'status-pill status-draft' }}">{{ $payment->status==='paid'?'Pago':'Pendente' }}</span></td><td>{{ $payment->paid_at?->format('d/m/Y H:i') ?: 'Aguardando assinatura' }}</td><td class="text-right">@if($payment->status==='paid')<span class="font-bold text-emerald-700">✓ Confirmado</span>@else<button type="button" class="btn-primary" data-sign-payment data-action="{{ route('payments.confirm',$payment) }}" data-name="{{ $payment->participant->full_name }}" data-amount="{{ number_format($payment->amount,2,',','.') }} {{ $paymentList->currency }}">Confirmar e assinar</button>@endif</td></tr>@endforeach</tbody></table></div><div class="p-5">{{ $payments->links() }}</div>
  </section>
</div>
<dialog id="payment-signature-dialog" class="m-0 h-screen max-h-none w-screen max-w-none bg-stone-950 p-0 text-white backdrop:bg-stone-950/90"><form method="post" id="payment-signature-form" class="mx-auto flex min-h-screen max-w-6xl flex-col p-5 lg:p-10">@csrf<input type="hidden" name="signature" id="payment-signature-data"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-bold uppercase tracking-widest text-orange-400">Confirmar recebimento</p><h2 id="payment-person-name" class="mt-2 text-3xl font-bold"></h2><p class="mt-2 text-stone-400">Confirma que recebeu <strong id="payment-amount" class="text-xl text-white"></strong>?</p></div><button type="button" data-close-signature class="btn-secondary border-stone-600 text-white">Cancelar</button></div><div class="mt-6 flex-1 rounded-3xl bg-white p-3"><canvas id="payment-signature" class="h-full min-h-[45vh] w-full touch-none rounded-2xl bg-white" aria-label="Área para assinatura de confirmação do pagamento"></canvas></div><div class="mt-5 flex gap-3"><button type="button" id="clear-payment-signature" class="btn-secondary border-stone-600 text-white">Limpar assinatura</button><button class="btn-primary flex-1 text-lg">Confirmar pagamento</button></div></form></dialog>
@push('scripts')<script>
const dialog=document.querySelector('#payment-signature-dialog'),form=document.querySelector('#payment-signature-form'),canvas=document.querySelector('#payment-signature'),ctx=canvas.getContext('2d');let drawing=false,moved=false;function sizeCanvas(){const ratio=devicePixelRatio||1,rect=canvas.getBoundingClientRect();canvas.width=rect.width*ratio;canvas.height=rect.height*ratio;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#111'}function clearCanvas(){ctx.clearRect(0,0,canvas.width,canvas.height);moved=false}function point(event){const rect=canvas.getBoundingClientRect();return[event.clientX-rect.left,event.clientY-rect.top]}
document.querySelectorAll('[data-sign-payment]').forEach(button=>button.addEventListener('click',()=>{form.action=button.dataset.action;document.querySelector('#payment-person-name').textContent=button.dataset.name;document.querySelector('#payment-amount').textContent=button.dataset.amount;dialog.showModal();requestAnimationFrame(()=>{sizeCanvas();clearCanvas()})}));canvas.addEventListener('pointerdown',event=>{drawing=true;ctx.beginPath();ctx.moveTo(...point(event));canvas.setPointerCapture(event.pointerId)});canvas.addEventListener('pointermove',event=>{if(!drawing)return;ctx.lineTo(...point(event));ctx.stroke();moved=true});canvas.addEventListener('pointerup',()=>drawing=false);canvas.addEventListener('pointercancel',()=>drawing=false);document.querySelector('#clear-payment-signature').addEventListener('click',clearCanvas);document.querySelector('[data-close-signature]').addEventListener('click',()=>dialog.close());form.addEventListener('submit',event=>{if(!moved){event.preventDefault();alert('A pessoa deve assinar para confirmar o recebimento.');return}document.querySelector('#payment-signature-data').value=canvas.toDataURL('image/png')});
</script>@endpush
@endsection
