@extends('layouts.app',['title'=>'Presenças — Sinala'])
@section('content')
<div><p class="eyebrow">PRESENÇAS</p><h1 class="mt-2 text-4xl font-bold">Registos de presença</h1><p class="mt-2 text-stone-500">Histórico paginado de assinaturas recolhidas.</p></div>
<form method="get" class="mt-7 grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_minmax(220px,1fr)_160px_120px_auto]">
  <label class="field">Pesquisar<input name="search" value="{{ request('search') }}" placeholder="Nome do participante"></label><label class="field">Evento<select name="event"><option value="">Todos os eventos</option>@foreach($events as $event)<option value="{{ $event->id }}" @selected((string)$event->id===request('event'))>{{ $event->name }}</option>@endforeach</select></label><label class="field">Tipo<select name="type"><option value="">Todos</option><option value="check_in" @selected(request('type')==='check_in')>Entrada</option><option value="check_out" @selected(request('type')==='check_out')>Saída</option></select></label><label class="field">Por página<select name="per_page">@foreach([10,20,50,100] as $size)<option @selected((int)request('per_page',20)===$size)>{{ $size }}</option>@endforeach</select></label><div class="flex items-end gap-2"><button class="btn-primary">Filtrar</button><a class="btn-secondary" href="{{ route('organization.attendance') }}">Limpar</a></div>
</form>
<section class="mt-5 overflow-hidden rounded-3xl bg-white"><div class="overflow-x-auto"><table class="w-full min-w-[960px] text-left"><caption class="sr-only">Presenças filtradas</caption><thead><tr><th>Participante</th><th>Evento</th><th>Tipo</th><th>Data e hora</th><th>Assinatura</th><th></th></tr></thead><tbody>@forelse($records as $record)<tr><td class="font-semibold">{{ $record->participant->full_name }}</td><td><a class="hover:text-orange-600" href="{{ route('events.show',$record->event) }}">{{ $record->event->name }}</a></td><td>{{ $record->type === 'check_out' ? 'Saída' : 'Entrada' }}</td><td>{{ $record->recorded_at->format('d/m/Y H:i') }}</td><td><span class="{{ $record->signature ? 'badge-success' : 'status-pill status-draft' }}">{{ $record->signature ? 'Recolhida' : 'Pendente' }}</span></td><td class="text-right">@if($record->signature)<button type="button" class="btn-secondary min-h-10 px-4 text-sm" data-preview-signature data-signature-url="{{ route('attendance.signature',$record) }}" data-signature-name="{{ $record->participant->full_name }}">Ver assinatura</button>@else<span class="text-sm text-stone-400">—</span>@endif</td></tr>@empty<tr><td colspan="6" class="py-12 text-center text-stone-400">Nenhuma presença corresponde aos filtros.</td></tr>@endforelse</tbody></table></div></section><div class="mt-6">{{ $records->links() }}</div>
<dialog id="signature-preview" class="w-full max-w-3xl rounded-3xl border-0 p-0 shadow-2xl backdrop:bg-stone-950/70"><div class="bg-white"><div class="flex items-center justify-between border-b border-stone-200 px-6 py-4"><div><p class="text-xs font-black tracking-[.18em] text-orange-600">ASSINATURA</p><h2 id="signature-preview-title" class="mt-1 text-xl font-bold text-stone-950">Pré-visualização</h2></div><button type="button" class="btn-secondary min-h-10 px-4 text-sm" data-close-signature>Fechar</button></div><div class="bg-stone-100 p-6"><img id="signature-preview-image" alt="Assinatura do participante" class="mx-auto max-h-[70vh] w-auto max-w-full rounded-2xl bg-white p-3 shadow-sm"></div></div></dialog>
<script>const signatureDialog=document.querySelector('#signature-preview'),signatureImage=document.querySelector('#signature-preview-image'),signatureTitle=document.querySelector('#signature-preview-title');document.querySelectorAll('[data-preview-signature]').forEach(button=>button.addEventListener('click',()=>{signatureImage.src=button.dataset.signatureUrl;signatureTitle.textContent=`Assinatura de ${button.dataset.signatureName}`;signatureDialog.showModal();}));document.querySelector('[data-close-signature]')?.addEventListener('click',()=>signatureDialog.close());signatureDialog?.addEventListener('click',e=>{if(e.target===signatureDialog)signatureDialog.close();});</script>
@endsection
