@extends('layouts.app',['title'=>'Configurar documentos — Sinala'])
@section('content')
@php($settings=$organization->report_settings ?? [])
<div><p class="eyebrow">DOCUMENTOS</p><h1 class="mt-2 text-4xl font-bold">Cabeçalho e assinaturas</h1><p class="mt-2 max-w-3xl text-stone-500">Estas configurações são exclusivas da {{ $organization->name }} e serão aplicadas automaticamente às listas de presença e de recebimento.</p></div>
<form method="post" enctype="multipart/form-data" action="{{ route('organization.documents.update') }}" class="mt-8 grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]">@csrf @method('put')
  <section class="grid gap-5 rounded-3xl bg-white p-6 sm:grid-cols-2 lg:p-8">
    <label class="field sm:col-span-2">Título do cabeçalho<input name="header_title" value="{{ old('header_title',$settings['header_title'] ?? $organization->name) }}" placeholder="Nome da organização ou programa"></label>
    <label class="field sm:col-span-2">Subtítulo<input name="header_subtitle" value="{{ old('header_subtitle',$settings['header_subtitle'] ?? '') }}" placeholder="Unidade, programa ou descrição institucional"></label>
    <label class="field">Projecto<input name="project_name" value="{{ old('project_name',$settings['project_name'] ?? '') }}" placeholder="Nome do projecto"></label>
    <label class="field">Referência/financiamento<input name="funding_reference" value="{{ old('funding_reference',$settings['funding_reference'] ?? '') }}" placeholder="Contrato, financiador ou actividade"></label>
    <label class="field sm:col-span-2">Nota no rodapé<textarea name="footer_note" rows="3" placeholder="Texto opcional apresentado no final do documento">{{ old('footer_note',$settings['footer_note'] ?? '') }}</textarea></label>
    <label class="field sm:col-span-2">Logótipo da organização<input type="file" name="logo" accept="image/png,image/jpeg"><small class="mt-2 block font-normal text-stone-400">PNG ou JPG, até 2 MB. O ficheiro fica protegido e não possui acesso público directo.</small></label>
    @if($organization->logo_path)<label class="flex items-center gap-3 text-sm text-stone-600 sm:col-span-2"><input type="checkbox" name="remove_logo" value="1"> Remover o logótipo actual</label>@endif
    <label class="field sm:col-span-2">Faixa de logótipos do cabeçalho<input type="file" name="header_banner" accept="image/png,image/jpeg"><small class="mt-2 block font-normal text-stone-400">Use esta opção quando o documento deve apresentar vários parceiros ou financiadores no cabeçalho.</small></label>
    @if(!empty($settings['header_banner_path']))<label class="flex items-center gap-3 text-sm text-stone-600 sm:col-span-2"><input type="checkbox" name="remove_header_banner" value="1"> Remover a faixa de logótipos actual</label>@endif
  </section>
  <aside class="space-y-6"><section class="rounded-3xl bg-white p-6"><h2 class="text-xl font-bold">Pré-visualização do cabeçalho</h2><div class="mt-5 rounded-2xl border bg-stone-50 p-5">@if(!empty($settings['header_banner_path']))<img src="{{ route('organization.documents.header') }}" alt="Logótipos do cabeçalho" class="mb-5 w-full object-contain">@elseif($organization->logo_path)<img src="{{ route('organization.documents.logo') }}" alt="Logótipo actual" class="mb-5 max-h-16 max-w-40 object-contain">@else<x-brand-logo class="mb-5 h-10 w-auto" />@endif<strong class="block">{{ $settings['header_title'] ?? $organization->name }}</strong><small class="mt-1 block text-stone-500">{{ $settings['header_subtitle'] ?? 'Lista oficial da organização' }}</small></div></section>
  <section class="rounded-3xl bg-white p-6"><h2 class="text-xl font-bold">Responsáveis que assinam</h2><p class="mt-2 text-sm text-stone-500">Seleccione no máximo duas contas.</p><div class="mt-4 space-y-3">@foreach($organization->users as $user)<label class="flex items-center gap-3 rounded-xl border p-4"><input type="checkbox" name="signatory_user_ids[]" value="{{ $user->id }}" @checked(in_array($user->id,old('signatory_user_ids',$settings['signatory_user_ids'] ?? [])))><span><strong class="block text-sm">{{ $user->name }}</strong><small class="text-stone-400">{{ $user->roles->pluck('name')->join(', ') }}</small></span></label>@endforeach</div></section></aside>
  <div class="flex gap-3 xl:col-span-2"><a class="btn-secondary" href="{{ route('organization.reports') }}">Cancelar</a><button class="btn-primary">Guardar configuração</button></div>
</form>
@endsection
