@extends('layouts.app',['title'=>'Pagamentos — Sinala'])
@section('content')
<div><p class="eyebrow">PAGAMENTOS</p><h1 class="mt-2 text-4xl font-bold">Pagamentos e subsídios</h1><p class="mt-2 text-stone-500">Valores e confirmações, consultados com processamento no servidor.</p></div>
<form method="get" class="mt-7 grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-2 xl:grid-cols-[minmax(220px,1fr)_minmax(220px,1fr)_160px_120px_auto]">
  <label class="field">Pesquisar<input name="search" value="{{ request('search') }}" placeholder="Nome do participante"></label>
  <label class="field">Evento<select name="event"><option value="">Todos os eventos</option>@foreach($events as $event)<option value="{{ $event->id }}" @selected((string)$event->id===request('event'))>{{ $event->name }}</option>@endforeach</select></label>
  <label class="field">Estado<select name="status"><option value="">Todos</option><option value="pending" @selected(request('status')==='pending')>Pendente</option><option value="paid" @selected(request('status')==='paid')>Pago</option><option value="cancelled" @selected(request('status')==='cancelled')>Cancelado</option></select></label>
  <label class="field">Por página<select name="per_page">@foreach([10,20,50,100] as $size)<option @selected((int)request('per_page',20)===$size)>{{ $size }}</option>@endforeach</select></label>
  <div class="flex items-end gap-2"><button class="btn-primary">Filtrar</button><a class="btn-secondary" href="{{ route('organization.payments') }}">Limpar</a></div>
</form>
<section class="mt-5 overflow-hidden rounded-3xl bg-white"><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left"><caption class="sr-only">Pagamentos filtrados</caption><thead><tr><th>Participante</th><th>Lista</th><th>Evento</th><th>Valor</th><th>Estado</th><th>Confirmação</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td class="font-semibold">{{ $payment->participant->full_name }}</td><td><a class="hover:text-orange-600" href="{{ route('payments.lists.show',$payment->paymentList) }}">{{ $payment->paymentList->name }}</a></td><td><a class="hover:text-orange-600" href="{{ route('events.show',$payment->paymentList->event) }}">{{ $payment->paymentList->event->name }}</a></td><td class="font-semibold">{{ number_format($payment->amount,2,',','.') }} {{ $payment->paymentList->currency }}</td><td><span class="{{ $payment->status === 'paid' ? 'badge-success' : 'status-pill status-draft' }}">{{ ['paid'=>'Pago','pending'=>'Pendente','cancelled'=>'Cancelado'][$payment->status] ?? $payment->status }}</span></td><td>{{ $payment->paid_at?->format('d/m/Y H:i') ?: '—' }}</td></tr>@empty<tr><td colspan="6" class="py-12 text-center text-stone-400">Nenhum pagamento corresponde aos filtros.</td></tr>@endforelse</tbody></table></div></section>
<div class="mt-6">{{ $payments->links() }}</div>
@endsection
