<!doctype html><html lang="pt-MZ"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><meta name="robots" content="noindex,nofollow,noarchive"><title>{{ $title ?? 'Sinala' }}</title>@vite(['resources/css/app.css','resources/js/app.js'])@livewireStyles</head>
<body class="min-h-screen bg-[#f7f7f5] text-stone-950 antialiased"><a href="#main" class="sr-only focus:not-sr-only focus:fixed focus:z-50 focus:bg-white focus:p-4">Saltar para o conteúdo</a>
@auth
<div class="min-h-screen lg:grid lg:grid-cols-[244px_minmax(0,1fr)]">
  <aside class="hidden border-r border-stone-200 bg-[#f1f1ef] lg:flex lg:flex-col">
    <div class="flex h-20 items-center border-b border-stone-200 px-6"><a href="{{ auth()->user()->is_super_admin ? route('admin.plans.index') : route('dashboard') }}" aria-label="Sinala — página inicial"><x-brand-logo /></a></div>
    <div class="px-4 py-5">
      <label class="relative block"><span class="sr-only">Pesquisar</span><span class="absolute left-3 top-2.5 text-stone-400">⌕</span><input class="h-10 w-full rounded-xl border border-stone-200 bg-white pl-9 pr-3 text-sm" placeholder="Pesquisar"></label>
      <p class="mt-7 px-3 text-[10px] font-bold uppercase tracking-[.16em] text-stone-400">{{ auth()->user()->is_super_admin ? 'Plataforma' : 'Operações' }}</p>
      <nav class="mt-2 space-y-1">@if(auth()->user()->is_super_admin)<a class="nav-link {{ request()->routeIs('admin.plans.*')?'active':'' }}" href="{{ route('admin.plans.index') }}"><span>◇</span> Planos</a>@else<a class="nav-link {{ request()->routeIs('dashboard')?'active':'' }}" href="{{ route('dashboard') }}"><span>⌂</span> Visão geral</a><a class="nav-link {{ request()->routeIs('events.*')?'active':'' }}" href="{{ route('events.index') }}"><span>◇</span> Eventos</a><a class="nav-link {{ request()->routeIs('organization.participants')?'active':'' }}" href="{{ route('organization.participants') }}"><span>♙</span> Participantes</a><a class="nav-link {{ request()->routeIs('organization.attendance')?'active':'' }}" href="{{ route('organization.attendance') }}"><span>✓</span> Presenças</a><a class="nav-link {{ request()->routeIs('organization.payments')?'active':'' }}" href="{{ route('organization.payments') }}"><span>↗</span> Pagamentos</a><a class="nav-link {{ request()->routeIs('organization.reports')?'active':'' }}" href="{{ route('organization.reports') }}"><span>▤</span> Relatórios</a>@endif</nav>
    </div>
    <div class="mt-auto border-t border-stone-200 p-4"><div class="flex items-center gap-3 rounded-xl bg-white p-3"><span class="grid size-9 shrink-0 place-items-center rounded-full bg-orange-100 text-xs font-bold text-orange-700">{{ collect(explode(' ',auth()->user()->name))->map(fn($n)=>mb_substr($n,0,1))->take(2)->join('') }}</span><div class="min-w-0 flex-1"><strong class="block truncate text-sm">{{ auth()->user()->name }}</strong><small class="block truncate text-stone-400">{{ auth()->user()->is_super_admin ? 'Super Administrador' : auth()->user()->organization?->name }}</small></div><form method="post" action="{{ route('logout') }}">@csrf<button title="Terminar sessão" class="text-stone-400 hover:text-orange-600">↗</button></form></div></div>
  </aside>
  <div class="min-w-0 pb-20 lg:pb-0"><header class="flex h-20 items-center justify-between border-b border-stone-200 bg-white px-4 sm:px-7"><a class="lg:hidden" aria-label="Sinala — página inicial" href="{{ auth()->user()->is_super_admin ? route('admin.plans.index') : route('dashboard') }}"><x-brand-logo class="h-9 w-auto" /></a><div class="hidden lg:block"><p class="text-xs text-stone-400">{{ auth()->user()->organization?->name ?? 'Administração da plataforma' }}</p><strong class="text-sm">{{ now()->translatedFormat('d \d\e F \d\e Y') }}</strong></div><div class="flex items-center gap-2"><button aria-label="Notificações" class="grid size-11 place-items-center rounded-xl border border-stone-200 bg-white">♢</button>@if(auth()->user()->is_super_admin)<a href="{{ route('admin.plans.create') }}" class="btn-primary">+ Novo plano</a>@else<a href="{{ route('events.create') }}" class="btn-primary"><span class="sm:hidden">+</span><span class="hidden sm:inline">+ Novo evento</span></a>@endif</div></header>
@endauth
<main id="main" class="{{ auth()->check() ? 'p-4 sm:p-7' : '' }}">@if(session('success'))<div role="status" class="mb-5 rounded-xl bg-emerald-100 p-4 text-emerald-900">{{ session('success') }}</div>@endif @if($errors->any())<div role="alert" class="mb-5 rounded-xl bg-red-100 p-4 text-red-900"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif {{ $slot ?? '' }}@yield('content')</main>
@auth
@if(!auth()->user()->is_super_admin)<nav aria-label="Navegação móvel" class="fixed inset-x-0 bottom-0 z-40 overflow-x-auto border-t border-stone-200 bg-white lg:hidden"><div class="grid min-w-[620px] grid-cols-6 px-2"><a class="mobile-nav" href="{{ route('dashboard') }}">⌂<small>Visão geral</small></a><a class="mobile-nav" href="{{ route('events.index') }}">◇<small>Eventos</small></a><a class="mobile-nav" href="{{ route('organization.participants') }}">♙<small>Participantes</small></a><a class="mobile-nav" href="{{ route('organization.attendance') }}">✓<small>Presenças</small></a><a class="mobile-nav" href="{{ route('organization.payments') }}">↗<small>Pagamentos</small></a><a class="mobile-nav" href="{{ route('organization.reports') }}">▤<small>Relatórios</small></a></div></nav>@endif</div></div>
@endauth
@livewireScripts @stack('scripts')</body></html>
