<!doctype html><html lang="pt-MZ"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Assinar — {{ $event->name }}</title>@vite(['resources/css/app.css','resources/js/app.js'])</head><body class="min-h-screen bg-stone-950 text-white"><main class="mx-auto max-w-6xl p-5 lg:p-10"><header class="flex justify-between"><div><p class="text-orange-400">MODO DE ASSINATURA</p><h1 class="mt-2 text-3xl font-bold">{{ $event->name }}</h1><p class="text-stone-400">{{ $event->location }} · {{ $event->starts_on->format('d/m/Y') }}</p></div><a class="btn-secondary bg-white text-stone-950" href="{{ route('events.show',$event) }}">Sair</a></header>@if(session('success'))<div class="my-6 rounded-2xl bg-emerald-500 p-5 text-xl font-bold">✓ {{ session('success') }}</div>@endif
@if($event->isClosed())<div class="mt-8 rounded-3xl bg-white p-8 text-stone-950"><h2 class="text-2xl font-bold">Evento encerrado</h2><p class="mt-2 text-stone-600">Este evento foi fechado e já não é possível registar novas presenças.</p></div></main>
@else
<form method="post" action="{{ route('attendance.store',$event) }}" id="signature-form" class="mt-8">@csrf<div class="grid gap-5 md:grid-cols-3"><label class="field dark">Participante<select name="participant_id" required><option value="">Procure o seu nome</option>@foreach($event->participants as $p)<option value="{{ $p->id }}">{{ $p->full_name }}</option>@endforeach</select></label><label class="field dark">Dia<select name="event_day_id" required>@foreach($event->days as $day)<option value="{{ $day->id }}">{{ $day->date->format('d/m/Y') }}</option>@endforeach</select></label><label class="field dark">Tipo<select name="type"><option value="check_in">Entrada</option>@if($event->requires_check_out)<option value="check_out">Saída</option>@endif</select></label></div><div class="mt-6 rounded-3xl bg-white p-3"><canvas id="signature" class="h-[45vh] w-full touch-none rounded-2xl bg-white" aria-label="Área para desenhar assinatura"></canvas></div><input type="hidden" name="signature" id="signature-data"><div class="mt-5 flex gap-4"><button type="button" id="clear-signature" class="btn-secondary bg-white text-stone-950">Limpar assinatura</button><button class="btn-primary flex-1 text-lg">Confirmar presença</button></div></form></main>
@endif
@unless($event->isClosed())
<script>const c=document.querySelector('#signature'),x=c.getContext('2d');let drawing=false,moved=false;function size(){const d=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=r.width*d;c.height=r.height*d;x.scale(d,d);x.lineWidth=3;x.lineCap='round';x.strokeStyle='#111'}size();function point(e){const r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return [p.clientX-r.left,p.clientY-r.top]}c.addEventListener('pointerdown',e=>{drawing=true;moved=false;x.beginPath();x.moveTo(...point(e));c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drawing)return;x.lineTo(...point(e));x.stroke();moved=true});c.addEventListener('pointerup',()=>drawing=false);document.querySelector('#clear-signature').onclick=()=>{x.clearRect(0,0,c.width,c.height);moved=false};document.querySelector('#signature-form').onsubmit=e=>{if(!moved){e.preventDefault();alert('Desenhe a sua assinatura.');return}document.querySelector('#signature-data').value=c.toDataURL('image/png')};</script>
@endunless
</body></html>
